routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\DashboardController;
use App\Http\Controllers\Web\DispositionController;
use App\Http\Controllers\Web\DivisionController;
use App\Http\Controllers\Web\InboxController;
use App\Http\Controllers\Web\NotificationController;
use App\Http\Controllers\Web\OutboxController;
use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\TypeController;
use App\Http\Controllers\Web\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'auth'], function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/item', [DashboardController::class, 'index'])->name('dashboarddot');
    Route::get('/laporan', [ReportController::class, 'index'])->name('report.index');
    Route::resource('inbox', InboxController::class);
    Route::resource('outbox', OutboxController::class);
    Route::resource('type', TypeController::class);
    Route::group(['role:superadmin'], function () {
        Route::resource('user', UserController::class);
    });
    Route::resource('disposition', DispositionController::class);
    Route::resource('division', DivisionController::class);
    Route::get('/notifMemo/{id?}', [NotificationController::class, 'memo'])->name('notif.memo');
    Route::get('/notifInbox/{id}', [NotificationController::class, 'inbox'])->name('notif.inbox');
    Route::get('/notifOutbox/{id}', [NotificationController::class, 'outbox'])->name('notif.outbox');
});

app/Http/Controllers/Web/TypeController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Type;
use Carbon\Carbon;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::all();
        return view('pages.type.index', compact('types', $types));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Type::create([
            'name' => $request->name,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Type $type)
    {
        $type->delete();
        return redirect()->back();
    }
}

resources/views/pages/type/index.blade.php
@extends('layouts.dashboard')
@section('title')

@if (Request::path() != '/')
@php
$paths = explode('/', Request::path());
$len = count($paths)-1;
echo ucfirst($paths[$len]);
@endphp
@else
Dashboard
@endif
@endsection
@section('header')
Jenis Surat
@endsection
@section('content')
<div class="card">
    <div class="card-header">
      <h4>Data Surat Masuk</h4>
      <div class="card-header-action">
        <button class="btn btn-primary" id="addType">
          <i class="fas fa-plus"></i>
          <span>Tambah Jenis Surat</span>
        </button>
      </div>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <tbody>
              <tr>
                <th>No</th>
                <th>Jenis Surat</th>
                <th style="text-align: center">Action</th>
              </tr>
              @foreach ($types as $key => $type)
              <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$type->name}}</td>
                    <td>
                        <form action="{{ route('type.destroy', $type->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer text-right" modal-part>
        <nav class="d-inline-block">
          <ul class="pagination mb-0">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1"><i class="fas fa-chevron-left"></i></a>
            </li>
            <li class="page-item active"><a class="page-link" href="#">1 <span class="sr-only">(current)</span></a></li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
@endsection
@section('modal')
<div class="modal fade" id="modal_tambah" tabindex="-1" role="dialog" aria-labelledby="modal_tambah" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal-set-resiLabel">Tambah Jenis Surat Baru</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('type.store')}}" method="POST" id="form-add-type-data" enctype="multipart/form-data">
          @csrf
          <div class="modal-body row">
            <div class="form-group col-md-12">
              <label for="">Nama Jenis Surat</label>
              <input type="text" class="form-control" name="name">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $('#addType').on('click', () => {
          $('#modal_tambah').modal('show')
        });
</script>
@endsection