routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\DashboardController;
use App\Http\Controllers\Web\DispositionController;
use App\Http\Controllers\Web\DivisionController;
use App\Http\Controllers\Web\InboxController;
use App\Http\Controllers\Web\NotificationController;
use App\Http\Controllers\Web\OutboxController;
use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\TypeController;
use App\Http\Controllers\Web\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'auth'], function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/item', [DashboardController::class, 'index'])->name('dashboarddot');
    Route::get('/laporan', [ReportController::class, 'index'])->name('report.index');
    Route::resource('inbox', InboxController::class);
    Route::resource('outbox', OutboxController::class);
    Route::resource('type', TypeController::class);
    Route::group(['role:superadmin'], function () {
        Route::resource('user', UserController::class);
    });
    Route::resource('disposition', DispositionController::class);
    Route::resource('division', DivisionController::class);
    Route::get('/notifMemo/{id?}', [NotificationController::class, 'memo'])->name('notif.memo');
    Route::get('/notifInbox/{id}', [NotificationController::class, 'inbox'])->name('notif.inbox');
    Route::get('/notifOutbox/{id}', [NotificationController::class, 'outbox'])->name('notif.outbox');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Web/UserController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $roles = Role::all();
        return view('pages.users.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = User::with('roles')->where('id','=',$id)->first();
        return response()->json([
            'status'    =>  1,
            'data'      =>  $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->removeRole($user->roles[0]->name);
        $user->assignRole($request->roles);
        if ($request->password) {
            $user->password = bcrypt($request->password);
        }
        $user->save();

        toast('User berhasil di edit', 'success');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->destroy();

        return redirect()->back()->with('success', 'berhasil hapus user');
    }
}

resources/views/pages/users/index.blade.php
@extends('layouts.dashboard')
@section('title')

@if (Request::path() != '/')
@php
$paths = explode('/', Request::path());
$len = count($paths)-1;
echo ucfirst($paths[$len]);
@endphp
@else
Dashboard
@endif
@endsection
@section('header')
Manajemen User
@endsection
@section('content')
<!-- Main Content -->
<div class="section-body">

  <div class="card">
    <div class="card-header">
      <h4>Data User</h4>
      <div class="card-header-action">
        @role('admin')
        <button class="btn btn-primary" id="adduser">
          <i class="fas fa-plus"></i>
          <span>Tambah User</span>
        </button>
        @endrole
      </div>
    </div>
    <div class="card-body p-0">
      <div class="table-responsive">
        <table class="table table-striped table-md">
          <tbody>
            <tr>
              <th>No</th>
              <th>Nama</th>
              <th>Email</th>
              <th>Role</th>
              <th style="text-align: center">Action</th>
            </tr>
            @foreach ($users as $key => $user)
            <tr>
                @if ($user->roles[0]->name != 'superadmin')
                <td>{{$key+1}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->roles[0]->name}}</td>
                <td>
                    @role('superadmin')
                    <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                    <button type="button" class="btn btn-warning" onclick="setIndex({{$user->id}})"><i class="far fa-edit"></i></button>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                    </form>
                    @endrole
                    {{-- modal_edit{{$key}} --}}
                    {{-- <button onclick="alert('modal_edit{{$key}}'); document.getElementById('modal_edit{{$key}}').classList.toggle('show')"><i class="far fa-edit"></i></button> --}}
                </td>
                @endif
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer text-right" modal-part>
      <nav class="d-inline-block">
        <ul class="pagination mb-0">
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1"><i class="fas fa-chevron-left"></i></a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1 <span class="sr-only">(current)</span></a></li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>
@endsection
@section('modal')
    <div class="modal" id="modal_tambah" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="modal_title"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form action="" id="form-edit-user" method="POST">
                <input type="text" name="_method" id="form_method" hidden>
                @csrf
                <div class="form-group">
                    <label for="form_name">Name</label>
                    <input type="text" class="form-control" id="form_name" placeholder="Enter name" name="name">
                </div>
                <div class="form-group">
                    <label for="form_email">Email</label>
                    <input type="email" class="form-control" id="form_email" placeholder="Enter email" name="email">
                </div>
                <div class="form-group">
                    <label for="form_password">Password</label>
                    <input type="password" class="form-control" id="form_password" placeholder="Password" name="password">
                </div>
                <div class="form-group">
                    <label for="form_password">Role</label>
                    <select name="roles" id="form_roles">
                        @foreach ($roles as $role)
                            <option value="{{$role->name}}">{{$role->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </form>
            </div>
        </div>
        </div>
    </div>
@endsection
@section('script')
<script>
    // $('#adduser').on('click', () => {
    //     $('#modal_tambah').modal('show')
    // });
    function setIndex(id) {
        index = id;
        console.log(index);
        var url = "{{route('user.show', ":id ")}}";
        url = url.replace(":id", id);
        $.ajax({
            type: 'GET',
            url: url,
            success: function(data) {
                console.log(data);
                $('#modal_tambah').modal('show')
                $("#modal_title").html('Modal Edit')
                $("#form_method").val("PATCH")
                $("#form_name").val(data.data.name)
                $("#form_email").val(data.data.email)
                $("#form_roles").val(data.data.roles[0].name)
                var formAction = "{{route('user.update', ":id")}}";
                formAction = formAction.replace(':id', id);
                $("#form-edit-user").attr("action", formAction);
            },
        });
    }
</script>
@endsection